### ISSUE TITLE
Buggy moves and game doesn't stop

### ISSUE THREAD

**Issue by berkaygunduzz** [CorruptedArk/open-chaos-chess#17] opened 2020-11-30 08:38 UTC
**Describe the bug**
Buggy moves (it can happen anytime but playing fast increases possibility) and game doesn't stop when i even won

**To Reproduce**
1. Play a game (especially fast)

**Expected behavior**

**Screenshots**
If it's not enough i can share full mp4 video
High Res
![bug](https://user-images.githubusercontent.com/70534725/100586270-ee3daa00-32ff-11eb-8b92-adaa4c0be2e1.gif)
Low Res
![bug_low](https://user-images.githubusercontent.com/70534725/100586295-f990d580-32ff-11eb-893f-9e462c167fa1.gif)

**Smartphone (please complete the following information):**
 - Device: Huawei P10
 - OS: Android 9
 - Version: EMUI 9.1.0
 - Build Location: F-Droid

**Comment by CorruptedArk** [comment] 2020-11-30 08:48
This is a real tricky one to understand. No matter how quickly I press the pieces when I play, I can't reproduce the issue.

**Comment by berkaygunduzz** [comment] 2020-11-30 09:02
A long time ago i tried to make a game, i had a similar bug, i've fixed it with seperating render (display activities) and update (main activities) and make update fixed to 60 for second. Sorry for i I didn't study to your code but can it about that?

**Comment by CorruptedArk** [comment] 2020-11-30 09:17
I'm not sure. The game is pretty heavily multi-threaded to prevent the UI from completely freezing during a move, so the exact logic is complicated.

**Comment by CorruptedArk** [comment] 2020-11-30 09:25
I'm not sure if this is a problem with the game or a problem with your phone. Does this problem occur when your battery is fully charged? Is your phone rooted or running any extra software in the background?

**Comment by CorruptedArk** [comment] 2020-11-30 09:26
I'm testing on Android 9 as well, so it's not an API issue

**Comment by berkaygunduzz** [comment] 2020-11-30 09:28
K, i will try it with full charge, it can take some hours.
Btw I see in strings.xml file there is wait your turn warning, why i can't see it on my game? Is it just for multi?

**Comment by berkaygunduzz** [comment] 2020-11-30 09:32
It's not rooted and there was nothing running background except message programs.

**Comment by CorruptedArk** [comment] 2020-11-30 09:38
Weird, and at the moment that warning doesn't appear for me either. I think it stopped showing up a while back when I changed the way it blocks a move during animations.  I think it still shows up in multiplayer, though.

**Comment by CorruptedArk** [comment] 2020-11-30 09:41
Would you be willing to to try building from source or at least test the signed Github release? Maybe the problem has something to do with F-Droid's build

**Comment by berkaygunduzz** [comment] 2020-11-30 09:42
[This](https://github.com/CorruptedArk/open-chaos-chess/releases/tag/v1.6.5)?

**Comment by CorruptedArk** [comment] 2020-11-30 09:44
Yeah, that is built and signed directly by me

**Comment by berkaygunduzz** [comment] 2020-11-30 09:44
I can also try building from source if there is a guide for that

**Comment by CorruptedArk** [comment] 2020-11-30 09:47
I don't have a guide put together, so you don't have to do that if you don't already know how. The built release should be the same anyway

**Comment by berkaygunduzz** [comment] 2020-11-30 10:01
![bug](https://user-images.githubusercontent.com/70534725/100595521-0f0bfc80-330c-11eb-899f-57d1aecff902.gif)
GitHub release
Looks like it's about making moves before computer.

**Comment by berkaygunduzz** [comment] 2020-11-30 10:03
Still i try when fully charge, but i can't try while charging.
Also points are interesting and game doesn't count king and doesn't finish.

**Comment by berkaygunduzz** [comment] 2020-11-30 10:06
Is it supposed to queue move? Taking no moves isn't much better than it?

**Comment by berkaygunduzz** [comment] 2020-11-30 10:31
Ok, i tried with 30% charge and there was no buggy moves, probably at low battery processor slows down so it lags, but still i can't see wait your turn.

**Comment by CorruptedArk** [comment] 2020-11-30 17:21
Since this issue isn't a problem caused by the game itself and the warning not showing up is currently intended behavior, I'm closing this issue for now. I still may look into the warning, though.

**Closed** 2020-11-30 17:22 UTC

**Comment by berkaygunduzz** [comment] 2020-11-30 17:25
Thanks for your help anyway

**Comment by CorruptedArk** [comment] 2020-11-30 17:38
Of course, I'm glad to help as much as I can. Thank you for providing helpful feedback
