### ISSUE TITLE
Game can be reset while a peice is moving

### ISSUE THREAD

**Issue by Vulldozer** [CorruptedArk/open-chaos-chess#14] opened 2020-11-10 15:22 UTC
Usually when you click on the "new game" button the game lets you know "wait until the move has finished".

But if you rapidly click one of your chess peices and click new game at the same time, the game will be reset but the move will still be applied which can result in something likes this:

![Screenshot_20201110-171936_Open Chaos Chess](https://user-images.githubusercontent.com/59207724/98693402-eaf67480-2378-11eb-855f-1ed6afc8afa1.jpg)

It doesn't affect normal gameplay but I enjoy speedrunning the game and this bug can be an issue sometimes.

**Comment by CorruptedArk** [comment] 2020-11-10 17:25
This is an interesting issue, it's going to be a fun one to figure out for sure. My guess is that the move executing immediately after the check that the new game button does. That probably allows the game to reset at the same time as the move.

**Comment by CorruptedArk** [comment] 2020-11-10 17:34
Also, physically how are you holding your phone and pressing to achieve this, I'm struggling to reproduce the bug myself

**Comment by Vulldozer** [comment] 2020-11-10 18:35
> Also, physically how are you holding your phone and pressing to achieve this? I'm struggling to reproduce the bug myself.

I am unable to find a way to consistently replicate the bug, the only way I can do it again is by mashing buttons which can cause all sorts of wierd stuff like this:
![Screenshot_20201110-201552_Open Chaos Chess.jpg](https://user-images.githubusercontent.com/59207724/98716118-b5ab5000-2393-11eb-85ac-4ae95fb0f700.jpg)

I could link a recording of me performing it but I am not sure which video hosting website should I use (is an unlisted youtube video fine?)

**Comment by CorruptedArk** [comment] 2020-11-10 19:13
Wait, you got to the knights only mode without deliberately clicking on the knight in the main menu? And yeah any sort of video hosting should be fine

**Comment by Vulldozer** [comment] 2020-11-10 19:29
> Wait, you got to the knights only mode without deliberately clicking on the knight in the main menu? And yeah any sort of video hosting should be fine

Alright so I think there is 2 seperate bugs going on that arent related

The first I am still unable to replicate.

But the second which is the knight only mode appearing is probably because the knight is hidden under the logo [https://youtu.be/wu7QH4DpEys](https://youtu.be/wu7QH4DpEys)

**Comment by CorruptedArk** [comment] 2020-11-10 19:34
Okay, I'm going to probably  leave the knight one alone because that is mostly intended behavior, except for maybe blocking the action while underneath other views. Or maybe I'll bring it to the top layer. The first bug is unintended, and I'll have to think about how to fix it

**Comment by Vulldozer** [comment] 2020-11-10 20:08
Update: I figured out a way to replicate the bug that I mentioned at the start a.k.a "The game can be reset while a piece is moving".

Here is how to do it:
1) Click any of your chess pieces to move it.
2) While that piece is moving, keep tapping on a second piece.
3) The moment your second piece start moving you click "new game"

Outcome: Either the opponent will have a head-start or will get a duplicate piece, which both aren't supposed to happen.

Demonstration: [https://youtu.be/IU1fuQ4LEK4](https://youtu.be/IU1fuQ4LEK4)

**Comment by CorruptedArk** [comment] 2020-11-10 20:14
Alright, thank you for clearly and concisely listing the reproduction steps as well as providing a helpful video. I'll get on it as soon as I can

**Comment by CorruptedArk** [comment] 2020-11-12 03:10
This issue should be fixed in v1.6.4 or at least much harder to reproduce than it already is. I personally was unable to reproduce it at all, but maybe my reaction time is too slow. Either way, let me know if you run into the problem again and this issue can be reopened.

**Closed by CorruptedArk** 2020-11-12 03:10 UTC
